# Generated by Django 4.1.7 on 2023-03-29 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover',
            field=models.ImageField(blank=True, upload_to='covers/', verbose_name='عکس جلد'),
        ),
    ]
