# Generated by Django 4.0.5 on 2023-04-10 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='status',
            field=models.SmallIntegerField(default=1),
        ),
    ]
