# Generated by Django 4.0.5 on 2023-04-17 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_orders_discount_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderlistitems',
            name='order_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_list_item', to='shop.orders'),
        ),
    ]
