# Generated by Django 4.0.5 on 2023-04-17 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_orderlistitems_order_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderlistitems',
            old_name='price',
            new_name='pay_price',
        ),
        migrations.AddField(
            model_name='orderlistitems',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=10000, max_digits=20),
            preserve_default=False,
        ),
    ]
